name: "改进建议 - Feature Request"
description: "这是一个愿望箱。"

title: "[Feature]"
labels:
  - "Feature"
body:
  - type: "input"
    attributes:
      label: "版本号 - Version"
      placeholder: "vX.X"
    validations:
      required: true
  - type: "checkboxes"
    attributes:
      label: "分支 - Branch"
      options:
        - label: "Rindo"
          required: false
        - label: "Lindu"
          required: false
    validations:
      required: true
  - type: "checkboxes"
    attributes:
      label: "平台 - Platform"
      options:
        - label: "Windows.x86-64"
          required: false
        - label: "Android"
          required: false
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "功能描述 - Feature Description"
      placeholder: "留下你的宝贵意见～"
    validations:
      required: true